name: check PR to main branch

on:
  pull_request:
    branches:
    - master
jobs:
  ts-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm i
      - name: build
        run: |
          npm run build
      - name: test
        run: |
          npm run test